phoics/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from portal import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # this url is for admin page "/admin/"
    url(r'^admin/', admin.site.urls),
    # this is for user loggin in page "/"
    url(r'^$', views.front_page, name='front_page'),
    url(r'^phoics/', include('portal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.error404
handler400 = views.error400
handler500 = views.error500
handler403 = views.error403

portal/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as built_views
from django.contrib import admin
from portal import views
from django.contrib.auth.views import password_reset
from django.conf import settings
from django.conf.urls.static import static
from django_filters.views import FilterView



urlpatterns = [

    # url(r'^$', views.home, name='profile'),
    url(r'^$', views.newsfeed, name='newsfeed'),

    url(r'^profile/(?P<username>\w+)/$', views.home, name='profile'),

    url(r'^upload/(?P<username>\w+)/$', views.model_form_upload, name='model_form_upload'),

    url(r'^login/$', views.check_login, name='login'),

    # if user will logout it will render to login page
    url(r'^logout/$', built_views.logout, {'next_page': 'newsfeed'}, name='logout'),

    url(r'^information/(?P<username>\w+)/$', views.user_info, name="user_info"),


    url(r'^signup/$', views.signup, name='signup'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate,
        name='activate'),

    # url(r'^frontpage/$', views.front_page, name='front_page'),

    url(r'^passwordreset/$', password_reset,
        {'template_name': 'forget/password_reset_form.html'},
        name='password_reset'),

    url(r'^passwordreset/done/$', built_views.password_reset_done,
        {'template_name': 'forget/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        built_views.password_reset_confirm,
        {'template_name': 'forget/password_reset_confirm.html',
         'post_reset_redirect': 'login'},
        name='password_reset_confirm'),

    url(r'^profile/(?P<username>\w+)/edit/(?P<pk>\d+)$', views.doc_update, name='Doc_edit'),

    url(r'^profile/(?P<username>\w+)/delete/(?P<pk>\d+)$', views.doc_delete, name='Doc_delete'),
    url(r'comment/$', views.comment, name='comment'),

    url(r'^like/$', views.like, name='like'),
    url(r'^user_list/$', views.list_of_user, name='user_list'),
    url(r'^validate_username/$', views.validate_username, name='validate_username'),
    url(r'^validate_email/$', views.validate_emailid, name='validate_email'),
    url(r'^edit_image/rotate/$', views.rotate_image, name='rotate_image'),
    url(r'^edit_image/blur/$', views.blur_image, name='blur_image'),
    url(r'^edit_image/flip/$', views.flip_image, name='flip_image'),
    url(r'^edit_image/height/$', views.height_image, name='height_image'),
    url(r'^edit_image/width/$', views.width_image, name='width_image'),
    url(r'^edit_image/effect/$', views.effect_image, name='effect_image'),
    url(r'^search/$', views.search, name='search'),


   ]

portal/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db import models
import uuid
import os
from django.contrib import messages
from django.core.urlresolvers import reverse
from PIL import Image
from PIL import ImageFilter, ImageOps
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys


def get_profile_name(instance, filename):    # to give unique id to profile pic uploaded by using uuid
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('profile_pic', filename)


class Profile(models.Model):                # all details comming as user's profile info form get saved in this table
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    First_Name = models.CharField(max_length=100, blank=True)
    Last_Name = models.CharField(max_length=100, blank=True)
    City = models.CharField(max_length=30, blank=True)
    DOB = models.DateTimeField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to=get_profile_name, default='profile_pic/default_profile.jpg')
    bio = models.TextField(max_length=500, blank=True)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):                    # shows every object with username name
        return self.user.username


def get_file_name(instance, filename):               # to give unique id to images uploaded
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('documents', filename)

choice1 = (("PRIVATE", "Private"), ("PUBLIC", "Public"),)
choice2 = ((1, "Large"), (2, "Medium"),(3, "Small"))
choice3 = (('horizon', "Flip Horizontally"), ('vertical', "Flip Vertically"),('NONE', "None"))
choice4 = (('clock', "Clockwise"), ('anti', "Anticlockwise"), ('NONE', "None"))
choice5 = (('y', 'Yes'), ('n', 'No'))
choice6 = ((1, "None"), (2, "Aqua"), (3, "Seaform"), (4, "Grayscale"),
           (5, "Retro"), (6, "Edges"), (7, "Negative"), (8, 'Sepia'))


class Document(models.Model, object):                  # all details comming about a particular picture uploaded                                                      #  get saved in this table
    user = models.ForeignKey(User)
    status = models.CharField(max_length=7, choices=choice1, default="PUBLIC")
    width = models.IntegerField(blank=True, default=500, help_text="Enter positive value ")
    height = models.IntegerField(blank=True, default=500, help_text="Enter positive value ")
    flip = models.CharField(max_length=17, choices=choice3, default="NONE")
    rotate = models.CharField(max_length=15, choices=choice4, default='NONE')
    blur = models.CharField(max_length=5, choices=choice5, default='n')
    effect = models.IntegerField(choices=choice6, default=1)
    document = models.ImageField(upload_to=get_file_name)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    like_or_not = models.IntegerField(default=0)
    like_user = models.ManyToManyField(User, related_name='hello', blank=True)

    def __str__(self):
        return self.user.username

    def __unicode__(self):                  # gives a common name to objects
        return self.document

    def get_absolute_url(self):
        return reverse('model_form_upload', kwargs={'pk': self.pk})

    def save(self):
        im = Image.open(self.document)    #opens a particular image

        output = BytesIO()                #file is written into memory
        im = im.resize((self.width, self.height))
        if self.flip == 'horizon':
            im = im.transpose(Image.FLIP_LEFT_RIGHT)
        elif self.flip == 'vertical':
            im = im.transpose(Image.FLIP_TOP_BOTTOM)
        elif self.flip == 'NONE':
            pass

        if self.rotate == 'clock':
            im = im.rotate(270)
        elif self.rotate == 'anti':
            im = im.rotate(90)
        elif self.rotate == 'NONE':
            pass

        if self.blur == 'y':
            im = im.filter(ImageFilter.BLUR)
        elif self.blur == 'n':
            pass

        if self.effect == 1:
            im = im.convert('RGB')
            r, g, b = im.split()
            im = Image.merge('RGB', (r, g, b))
        elif self.effect == 2:
            im = im.convert('RGB')
            r, g, b = im.split()
            im = Image.merge('RGB', (b, g, r))
        elif self.effect == 3:
            im = im.convert('RGB')
            r, g, b = im.split()
            im = Image.merge('RGB', (g, r, b))
        elif self.effect == 4:
            width, height = im.size
            for i in range(width):
                for j in range(height):
                    r, g, b = im.getpixel((i,j))
                    c = int(round((r+g+b)/3))
                    im.putpixel((i,j),(c,c,c))
        elif self.effect == 5:
            im = im.convert('RGB')
            r, g, b = im.split()
            im = Image.merge('RGB', (r, b, g))
        elif self.effect == 6:
            im = im.filter(ImageFilter.FIND_EDGES)
        elif self.effect == 7:
            im = ImageOps.invert(im)
        elif self.effect == 8:
            width, height = im.size
            for i in range(width):
                for j in range(height):
                    r, g, b = im.getpixel((i,j))
                    c = int((round(r+g+b)/3))
                    R, G, B = c+100, c+100, c
                    im.putpixel((i, j), (R, G, B))
        im.save(output, format='JPEG', quality=100)   # saving the image into the file in memory
        output.seek(0)

        self.document = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.document.name.split('.')[0],
                                             'image/jpeg', sys.getsizeof(output), None)

        try:
            this = Document.objects.get(id=self.id)
            if this.document == self.document:
                self.document = this.document
            else:
                this.document.delete(save=False)
        except:
            pass  # when new image
        super(Document, self).save()


@receiver(post_delete, sender=Document)
def document_post_delete_handler(sender, **kwargs):
    instance = kwargs['instance']
    storage, path = instance.document.storage, instance.document.path
    if (path != '.') and (path != '/') and (path != 'photo/') and (path != 'document/.'):
        storage.delete(path)


class Comments(models.Model):
    user = models.ForeignKey(User)
    document = models.ForeignKey(Document)
    comment = models.TextField(max_length=225)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

@receiver(post_save,sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    # here created is a boolean that tells new instance
    #  was created or an older instance was updated.
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

portal/forms.py
from django import forms
from django.forms import extras
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from portal.models import Document, Profile, Comments


"""
UserCreationForm contain password1 and password2(conf.password)
it also check both password must be same
"""


class SignUpPage(UserCreationForm):                 # renders a signup form to user with the help of template
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

class SearchUser(forms.Form):                 # renders a signup form to user with the help of template
    username = forms.CharField(max_length=500, widget=forms.TextInput(
        attrs={'placeholder': 'Enter name of user you need to search',}))

    class Meta:
        fields = ('username',)

class Info(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('First_Name', 'Last_Name', 'City', 'DOB', 'bio', 'profile_pic', )


class DocumentForm(forms.ModelForm):                   # to render to user a form where he can upload pictures
                                                       # it is connected to Document table in database
    class Meta:
        model = Document
        status = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()), empty_label=None)
        width = forms.IntegerField()
        height = forms.IntegerField()
        flip = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()), empty_label=None, widget =forms.Select(attrs={
            "onChange": 'loadPic()'}))

        rotate = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()), empty_label=None)
        blur = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()), empty_label=None)
        effect = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()), empty_label=None)
        fields = ('document', 'status')


class UpdateForm(forms.ModelForm):                     # renders a form update pictures uploaded
                                                       # it is connected to Document table in database
    class Meta:
        model = Document
        status = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()),
                                        empty_label=None)
        width = forms.IntegerField()
        height = forms.IntegerField()
        flip = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()),
                                      empty_label=None)
        rotate = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()),
                                         empty_label=None)
        blur = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()),
                                      empty_label=None)
        effect = forms.ModelChoiceField(queryset=Document.objects.filter(uploaded_at=datetime.now()),
                                        empty_label=None)
        fields = ('status', 'width','height', 'flip', 'rotate', 'blur', 'effect')

# class CommentForm(forms.ModelForm):
#
#     class meta:
#         model = Comments
#         fields = ('comment', )

portal/templates/portal/edit_image.html
{% load staticfiles %}
<!DOCTYPE html>
<html>


<head>
    <title>Edit Image</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'portal/Upload.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>




    <script>


    $(document).ready(function() {
        $('#id_width').change(function() {

            var width = $(this).val();
            console.log(width);
            if (width <= 0){
                $('#error_image_width').text("enter valid width");
                return false;
            }
            var imgid = $(".Form").attr("id");

            $.ajax({
                url: '{% url 'width_image' %}',
                data: {
                    'width': width,
                    'imgid': imgid
                },

                success: function (data) {


                        $( ".image-display" ).attr("src", "/media/" + data.img_source );
                }

            })
        });



        $('#id_height').change(function() {

            var height = $(this).val();

            if (height <= 0){
                $('#error_image_height').text("enter valid height");
                return false;
            }
        });


        $("#id_rotate").change(function () {
            var rotate = $(this).val();
            var imgid = $(".Form").attr("id");
            var img_source = $(".image-display").attr("id");

            $.ajax({
                url: '{% url 'rotate_image' %}',
                data: {
                    'rotate': rotate,
                    'imgid': imgid
                },

                success: function (data) {


                        $( ".image-display" ).attr("src", "/media/" + data.img_source );
                }

            })
        }) ;
         $("#id_blur").change(function () {
            var blur = $(this).val();
            var imgid = $(".Form").attr("id");
            var img_source = $(".image-display").attr("id");

            $.ajax({
                url: '{% url 'blur_image' %}',
                data: {
                    'blur': blur,
                    'imgid': imgid
                },

                success: function (data) {
                          console.log("blurring");

                        $( ".image-display" ).attr("src", "/media/" + data.img_source );
                }

            })
        }) ;

         $("#id_flip").change(function () {
            var flip = $("#id_flip").val();
            var imgid = $(".Form").attr("id");
            var img_source = $(".image-display").attr("id");
            var height = $("id_height").val();
            var width = $("id_width").val();
            var effect = $("id_effect").val();
            var rotate = $("id_rotate").val();
            var blur = $("id_blur").val();
            $.ajax({
                url: '{% url 'flip_image' %}',
                data: {
                    'flip': flip,
                    'imgid': imgid,
                    'height': height,
                    'width': width,
                    'effect': effect,
                    'rotate': rotate,
                    'blur': blur
                },

                success: function (data) {
                          console.log("flip");

                        $( ".image-display" ).attr("src", "/media/" + data.img_source );
                }

            })
        }) ;
         $("#id_effect").change(function () {
            var effect = $(this).val();
            var imgid = $(".Form").attr("id");
            var img_source = $(".image-display").attr("id");
            console.log("prev -:" + img_source);

            $.ajax({
                url: '{% url 'effect_image' %}',
                data: {
                    'effect': effect,
                    'imgid': imgid
                },

                success: function (data) {
                          console.log("effect");

                        $( ".image-display" ).attr("src", "/media/" + data.img_source );
                        console.log("new:-" + data.img_source);
                }

            })
        }) ;
    })
    </script>
    <script>
        function preview(event)
        {

            console.log("imagination");
            var reader = new FileReader();
            reader.onload = function()
            {
                var output = document.getElementById('output');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
</head>
    <body>
   <nav class="navbar sticky-top">
    <div class="container top">
        <a class="navbar-brand" href="{% url 'newsfeed' %}">PHOICS</a>
        <ul class="nav justify-content-end">

            <li class="nav-item"><a href="{% url 'newsfeed' %}" class="nav-link"><i class="fa fa-home" aria-hidden="true"></i> Newsfeed</a></li>
        <li class="nav-item>"><a class="nav-link" href="{% url 'profile' user.username %}">	<i class="fa fa-user" aria-hidden="true"></i> Profile</a> </li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
        </ul>
    </div>
</nav>
   {% if request.user.is_authenticated %}
        <div class="container main justify-content-center">
          <div class="row">
         <div class="col-md-4 preview">
                <img src="{{ updatex.document.url }}" alt="..." class="img-thumbnail image-display" id="{{ updatex.document.url }}"><br>
                        <h4>{{ user.username }}</h4><br>
         </div>
        <div class=" col-md-8 edit-detail Form" id="{{ updatex.id }}">
            {% if user.is_authenticated %}
                     <form method='post' enctype="multipart/form-data" onchange="preview(event)" class="">
                         {% csrf_token %}
{#    <div class="container">#}
{#        <div class="content heading"><p class="upload" ><p style="text-align: center; font-size: 200%">#}
{#            {{ user.username }}</p><br><br>{{ title }}</div>#}
{#        <div class="content form">#}
{#             <div class="Form" id="{{ updatex.id }}">#}
{##}
{#                    {% if request.user.is_authenticated %}#}
{##}
{#                         <form method='post' enctype="multipart/form-data" novalidate onsubmit="preview(event)">#}
{##}
{#                                {% csrf_token %}#}



                                 <div class="form-group row">
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.status.label_tag }}</strong></label>
                                     <div class="col-sm-8">

<select name="status" id="id_status" class="form-control">
  <option value="PRIVATE" selected="">Private</option>

  <option value="PUBLIC">Public</option>

</select>                                     </div><br>
                                      <p id="error_image_status" style="color: #ff0000">{{ form.status.errors }}
                                 </div>

                                 <div class="form-group row">
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.width.label_tag }}</strong></label>
                                     <div class="col-sm-8">
                                    <input type="number" name="width" value="500" id="id_width" class="form-control">
                                 </div><br>
                                      <p id="error_image_width" style="color: #ff0000">
                                      </p>
                                 </div>

                                 <div class="form-group row" >
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.height.label_tag }}</strong></label>
                                      <div class="col-sm-8">
                                          <input type="number" name="height" value="500" id="id_height" class="form-control"></div><br>
                                      <p id="error_image_height" style="color: #ff0000">
                                 </div>

                                 <div class=" form-group row" >
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.rotate.label_tag }}</strong></label>
                                      <div class="col-sm-8"><select name="rotate" id="id_rotate" class="form-control">
  <option value="clock">Clockwise</option>

  <option value="anti">Anticlockwise</option>

  <option value="NONE" selected>None</option>

                                      </select></div><br>
                                      <p id="error_image_rotate" style="color: #ff0000">
                                 </div>

                                 <div class="form-group row">
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.flip.label_tag }}</strong></label>
                                     <div class="col-sm-8"><select name="flip" id="id_flip" class="form-control">
  <option value="horizon">Flip Horizontally</option>

  <option value="vertical">Flip Vertically</option>

  <option value="NONE" selected>None</option>

                                     </select></div><br>
                                      <p id="error_image_flip" style="color: #ff0000">
                                 </div>

                                 <div class="form-group row" >
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.blur.label_tag }}</strong></label>
                                       <div class="col-sm-8"><select name="blur" id="id_blur" class="form-control">
  <option value="y">Yes</option>

  <option value="n" selected>No</option>

                                 </select></div><br>
                                      <p id="error_image_blur" style="color: #ff0000">
                                 </div>

                                 <div class="form-group row">
                                     <label for="name" class="col-sm-3 col-form-label"><strong>{{ form.effect.label_tag }}</strong></label>
                                     <div class="col-sm-8"><select name="effect" id="id_effect" class="form-control">
  <option value="1" selected>None</option>

  <option value="2">Aqua</option>

  <option value="3">Seaform</option>

  <option value="4">Grayscale</option>

  <option value="5">Retro</option>

  <option value="6">Edges</option>

  <option value="7">Negative</option>

  <option value="8">Sepia</option>

                                     </select></div><br>
                                      <p id="error_image_effect" style="color: #ff0000">
                                 </div>
                            <button class="button" type="submit">SUBMIT</button><br>
                         </form>
{#                    {% else %}#}
{#                    <h3>first logged in</h3>#}
                    {% endif %}

                 </div>
            </div>
    {% endif %}
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

portal/templates/portal/error_404.html
<!DOCTYPE html>
<html>
<head>
<style>
    @import url('https://fonts.googleapis.com/css?family=Raleway');
    div{
	    margin-top:20vh;
	    margin-left:10vw;
    }
    p{
	    font-family: 'Raleway';
	    font-size:150%;
    }
    span{
	     font-size:400%;
    }
    img{
	    height:10vh;
	    width:10vw;
    }
</style>
</head>
<body>
    <div>
{#        <img src="{% url 'portal/images/error_img.svg' %}">#}
	    <p><span>ERROR {{ name }} :</span><br> {{ title }}</p>
    </div>
</body>
</html>

portal/templates/portal/info.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>User Info</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'portal/Upload.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


     <script>

         function preview(evt)
         {
             {# FileList contain user selected files and index 0 means first file #}

             var reader = new FileReader();
             reader.onload = function()
             {
                 var output = document.getElementById('output');
                 output.src = reader.result;
             }
             reader.readAsDataURL(evt.target.files[0]);
         }
    </script>
</head>
<body>
   <nav class="navbar sticky-top">
    <div class="container top">
        <a class="navbar-brand" href="{% url 'newsfeed' %}">PHOICS</a>
        <ul class="nav justify-content-end">

            <li class="nav-item"><a href="{% url 'newsfeed' %}" class="nav-link"><i class="fa fa-home" aria-hidden="true"></i> Newsfeed</a></li>
        <li class="nav-item>"><a class="nav-link" href="{% url 'profile' user.username %}">	<i class="fa fa-user" aria-hidden="true"></i> Profile</a> </li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
        </ul>
    </div>
</nav>

    {% if request.user.is_authenticated %}
        <div class="container main justify-content-center">
          <div class="row">
         <div class="col-md-4 preview">
                <img src="{{ obj.profile_pic.url }}" alt="..." class="img-thumbnail" id="output"><br>
                        <h4>{{ user.username }}</h4><br>

{#         <button class="btn">Change Profile Picture</button><br><br>#}
        </div>
        <div class=" col-md-8 edit-detail">
            {% if user.is_authenticated %}
                     <form method='post' enctype="multipart/form-data" onchange="preview(event)" class="">
                         {% csrf_token %}

                             <div class="form-group row">
                                 <label for="name" class="col-sm-3 col-form-label"><strong><label for="id_First_Name">First Name:</label></strong></label>
                                 <div class="col-sm-8">
                                     <input class="form-control" type="text" name="First_Name" maxlength="100" id="id_First_Name" value="{{ obj.First_Name }}"><br>
                                 </div>

                             </div>

                             <div class="form-group row">
                                 <label for="name" class="col-sm-3 col-form-label"><strong><label for="id_Last_Name">Last Name:</label></strong></label>
                                 <div class="col-sm-8">
                                     <input class="form-control" type="text" name="Last_Name" maxlength="100" id="id_Last_Name"  value="{{ obj.Last_Name }}">
                                 </div>

                             </div>
                          <div class="form-group row">
                                 <label for="name" class="col-sm-3 col-form-label"><strong><label for="id_bio">About:</label></strong></label>
                                 <div class="col-sm-8">
                                     <textarea  class="form-control" name="bio" cols="40" rows="10" maxlength="500" id="id_bio" value="{{ obj.bio }}">
</textarea>
                                 </div>

                             </div>

                             <div class="form-group row">
                                 <label for="name" class="col-sm-3 col-form-label"><strong><label for="id_profile_pic">Change Picture:</label></strong></label>
                                 <div class="col-sm-8">
                                     <input class="form-control"type="file" name="profile_pic" id="id_profile_pic" />
                                 </div>

                             </div>


                         <button class="button" type="submit">SUBMIT</button><br>
                     </form>
                 {% endif %}
             </div>
         </div>
        {% endif %}

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>